### ISSUE TITLE
Rapido HF Mount

### ISSUE THREAD

**Issue by abstractFlo** [JackJack3231/MiniSB-Extruder-Mounts#1]
Hi, is it possible to create a Mount for the Rapdio HF too? I want the flexibility of this awesome MiniSB Extruder Mounts but i am using Rapido HF only in my printers :D

I hope this is possible 🙈  (i can do it in CAD too, but my experience is really low :D)

**Comment by JackJack3231** [comment]
I just added experimental versions of the cowlings using a extended air duct.
[Experimental Cowlings](https://github.com/JackJack3231/MiniSB-Extruder-Mounts/tree/main/Extruder_Mounts/_Experimental/RapidoHF)

You will also need the Hotend Mount from [Mavericks mod](https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/Maverick/MiniSB_Rapido/STLs/FS_Hotend_Mount_Phaetus_Rapido.stl)

I have not tested as my Rapido is currently in my Trident and I won't have time for at least one week.
In CAD everything looks fine.
So use at your own risk and let me know if it works for you.

The CAD-Files are also included so if there are some small issues you can try adjusting it yourself.

Commit: 599134eb163cda3329875077b44283df158a68ee

**Comment by abstractFlo** [comment]
Will test this :) thank you

**Comment by JackJack3231** [comment]
As I've seen a few reports of people using the Rapido Versions successfully I will close this issue for now.
