### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by KenVanHoeylandt** [JackJack3231/MiniSB-Extruder-Mounts#2]
Would you mind adding a license?
That way, it's more clear for people who would like to make some forks.
(I'm making an EBB36 variant)

**Comment by JackJack3231** [comment]
I knew I forgot something when I created this repo.
I added the GPL v3 License. 6f23fe9b279ba1b1e7a5ff590dcb635ee5be8601

**Comment by KenVanHoeylandt** [comment]
Awesome - thanks!
