### ISSUE TITLE
Support ZeroClick toolhead mount

### ISSUE THREAD

**Issue by hudrucan** [JackJack3231/MiniSB-Extruder-Mounts#4]
It's awesome project but it much be better if it's supported `ZeroClick` probe mount from this project: https://github.com/zruncho3d/ZeroClick

**Comment by JackJack3231** [comment]
I looked at this in the past and still want to add support,
however currently I'm quite busy and I have no idea when I will find the time to work on this.

**Comment by The1whokn0cks** [comment]
Also agree that this is a awesome project. It gives everyone options who doesn't love options. Sorry to hijack this topic but have you.ever.also thought about maybe having support for the klicky pcb as well? Would love to see a standard cowling with klicky pcb support.

https://www.printables.com/model/634341-voron-02-mini-sb-orbiter-20-with-klicky-pcb

I've only seen this, and while great, was looking for a full cowling like your standard STLs.

**Comment by JackJack3231** [comment]
With 2104ac3fffd3c31f0a55fcf4bde86b1b38ce579d a first iteration of a ZeroClick-Implementation has been added.
All parts except the Probe have been remade and also require special cowlings.
See https://github.com/JackJack3231/MiniSB-Extruder-Mounts/tree/main/Extruder_Mounts/_ZeroClick-Common for more information.

Until I get confirmation that this is working I will leave this issue open.

**Comment by hudrucan** [comment]
> With [2104ac3](https://github.com/JackJack3231/MiniSB-Extruder-Mounts/commit/2104ac3fffd3c31f0a55fcf4bde86b1b38ce579d) a first iteration of a ZeroClick-Implementation has been added. All parts except the Probe have been remade and also require special cowlings. See https://github.com/JackJack3231/MiniSB-Extruder-Mounts/tree/main/Extruder_Mounts/_ZeroClick-Common for more information.
> 
> Until I get confirmation that this is working I will leave this issue open.

Cool, sorry for late response, I will try it soon

**Comment by hudrucan** [comment]
@JackJack3231 it's working with offset version for aux fan mount on the left
Demo video below, thanks for your support. ❤️ 

https://github.com/JackJack3231/MiniSB-Extruder-Mounts/assets/64943146/58c689dd-c8a4-4233-990f-10c884d3c062


https://github.com/JackJack3231/MiniSB-Extruder-Mounts/assets/64943146/2e9bc00e-d49a-475d-becb-29f7da9e1d79

**Comment by JackJack3231** [comment]
Great to hear!
I'll close this issue for now.

If someone encounters any problems with the ZeroClick implementation feel free to create a new issue.
