### ISSUE TITLE
SuperPINDA mount

### ISSUE THREAD

**Issue by TheSiggiePop** [JackJack3231/MiniSB-Extruder-Mounts#5]
Hi,

thanks for the great design! To make nozzle-swaps a bit easier I have added a SuperPINDA probe. Would you be interested in including this in all schrouds?

Cheers,
Greg

![Screenshot 2023-12-13 115022](https://github.com/JackJack3231/MiniSB-Extruder-Mounts/assets/101189138/06ea8827-8cd7-4f99-bbd8-4e33d93b40cc)

**Comment by JackJack3231** [comment]
I like the idea.
Yes I am interested in adding it as an option for all shrouds, however my time is quite limited currently so it will probably be a few months until I can start working on this.

**Comment by TheSiggiePop** [comment]
Alright. If you get to it, do give me a shout. I can also send you a fusion file. It's a bit messy, but the design has been running reliably for a fair bit now.

**Comment by JackJack3231** [comment]
Added PINDA / M8 Inductive Probe mounts with d1ec6958f66f737c1fd9276e2b123d68056034a7

I tested it in my printer and it seems to work.

Closing this issue for now.
